In [1]:
# Find the number of negative integers in a row-wise / column-wise sorted matrix
import numpy as np

m = np.matrix([[-3, -2, -1, 1], [-2, 2, 3, 4],  [4, 5, 7, 8]])
m

matrix([[-3, -2, -1,  1],
        [-2,  2,  3,  4],
        [ 4,  5,  7,  8]])

In [2]:
# Since the matrix is already sorted column wise and row wise only need to keep checking until we hit the
# first non-negative number on each row or column, but doing each separately would be inefficient, as we
# would check entries that should be already discarded by the first pass through on the second one...
# But lets implement it anyway to see if we can find a better solution along the way:


def negatives(matrix):
    count = 0
    last_j = 0
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if matrix[i, j] < 0:
                count += 1
            else:
                if last_j != j:
                    j = matrix.shape[1]
            last_j = j 
    return count

# This should be O(n) and Ω(i), as we only go through each element of the matrix once.
# The Ω(i) can still be improved, as we are only using the fact that the rows of the matrix
# are sorted, but not the columns.

In [3]:
negatives(m)

4

In [4]:
# To account for both row and column sorting we can't traverse through the matrix normally, row per row,
# We need to travel "diagonally" checking the "right" and "bottom" nodes 


def negatives2(matrix):
    d = {(0, 0): 0}  # Create a dictionary to archive nodes that have already been visited
    result = recursive(0, 0, matrix, d)  
    return result


def recursive(i, j, matrix, d):
    count = 0
    if matrix[i, j] >= 0:
        return count  # If positive end chain and don't add to the count
    else:
        count += 1  # Otherwise add 1 to the negative number count
        if i == matrix.shape[0] or j == matrix.shape[1]:
            return count  # If its the last node on either row or column end chain 
        if (i + 1, j) not in d:  # Otherwise check if the next row node is already accounted for
            d.update({(i + 1, j): count})  
            count += recursive(i + 1, j, matrix, d)  # And if it isn't continue the chain trough that row
        if (i, j + 1) not in d:  # Do the same for the column
            d.update({(i, j + 1): count})
            count += recursive(i, j + 1, matrix, d)
    return count
    
#  Now this should have O(n) and Ω(1), as we check only what is absolutely needed in each row/column

In [5]:
negatives2(m)

4

In [6]:
m2 = np.matrix([[-3, -2, -2, 3], [-1, -1, 3, 4],  [4, 5, 7, 8]])
m2

matrix([[-3, -2, -2,  3],
        [-1, -1,  3,  4],
        [ 4,  5,  7,  8]])

In [7]:
negatives2(m2)

5

In [8]:
m3 = np.matrix([[1, 2, 2, 3], [1, 1, 3, 4],  [4, 5, 7, 8]])
m3

matrix([[1, 2, 2, 3],
        [1, 1, 3, 4],
        [4, 5, 7, 8]])

In [9]:
negatives2(m3)

0